version: "3.5"

services:
  jekyll:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "4004:4004"
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --config _config_local.yml -H 0.0.0.0 -t --force_polling --livereload --livereload-port 4004
