name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust based on your Jekyll version
          bundler-cache: true  # Cache Ruby dependencies

      # Step 3: Install dependencies
      - name: Install Jekyll and Dependencies
        run: |
          bundle install

      # Step 4: Build the Jekyll site
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
